export const QUOTES = [
    "One day or day one. You decide.",
    "Your habits define your future.",
    "Small steps every day.",
    "Consistency is key.",
    "Don't stop until you're proud.",
    "Focus on the progress, not the perfection.",
    "Dream big, start small.",
    "Action is the foundational key to all success.",
    "Believe you can and you're halfway there.",
    "Success is the sum of small efforts repeated day in and day out.",
    "The secret of your future is hidden in your daily routine.",
    "Do something today that your future self will thank you for.",
    "It always seems impossible until it's done.",
    "Don't watch the clock; do what it does. Keep going.",
    "You don't have to be great to start, but you have to start to be great.",
    "Success doesn't come from what you do occasionally, it comes from what you do consistently.",
    "The only way to do great work is to love what you do.",
    "Your time is limited, don't waste it living someone else's life.",
    "Discipline is doing what needs to be done, even if you don't want to do it.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "A year from now you may wish you had started today.",
    "Don't let yesterday take up too much of today.",
    "You are what you repeatedly do.",
    "Excellence is not an act, but a habit.",
    "Be stronger than your excuses.",
    "Hard work beats talent when talent doesn't work hard.",
    "Limitations live only in our minds.",
    "Great things never came from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something formidable.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes later becomes never. Do it now.",
    "Great things satisfy no one.",
    "Start where you are. Use what you have. Do what you can.",
    "Make each day your masterpiece.",
    "The distance between dreams and reality is action.",
    "Don't tell people your plans. Show them your results.",
    "No pressure, no diamonds.",
    "Stay foolish to stay sane.",
    "Run the day. Don't let it run you.",
    "Focus on your goal. Don't look in any direction but ahead.",
    "Every morning you have two choices: continue to sleep with your dreams, or wake up and chase them.",
    "You are capable of amazing things.",
    "If it doesn't challenge you, it won't change you.",
    "What you do today can improve all your tomorrows.",
    "Be the energy you want to attract.",
    "Your potential is endless.",
    "Fall seven times, stand up eight.",
    "Everything you can imagine is real.",
    "Hope is a waking dream.",
    "May your choices reflect your hopes, not your fears.",
    "Happiness depends upon ourselves.",
    "Turn your wounds into wisdom.",
    "Change the game, don't let the game change you.",
    "Simplicity is the ultimate sophistication.",
    "Whatever you are, be a good one.",
    "If you want to fly, give up everything that weighs you down.",
    "Doubt kills more dreams than failure ever will.",
    "I never lose. I either win or learn.",
    "Today is your opportunity to build the tomorrow you want.",
    "You are the artist of your own life. Don't hand the paintbrush to anyone else.",
    "Don't count the days, make the days count.",
    "Energy flows where attention goes.",
    "Be so good they can't ignore you.",
    "Just keep swimming.",
    "Life is 10% what happens to you and 90% how you react to it.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "The best way to predict the future is to create it.",
    "Well done is better than well said.",
    "Stay hungry, stay foolish.",
    "Growth begins at the end of your comfort zone.",
    "What defines us is how well we rise after falling.",
    "Make it happen. Shock everyone.",
    "Quiet the mind and the soul will speak.",
    "We are what we believe we are.",
    "Act as if what you do makes a difference. It does.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Never bend your head. Always hold it high. Look the world straight in the eye.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Believe in yourself and all that you are.",
    "There is no substitute for hard work.",
    "Strive for progress, not perfection.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Don't wait. The time will never be just right.",
    "Your life does not get better by chance, it gets better by change.",
    "Clear your mind of can't.",
    "Focus on being productive instead of busy.",
    "Do the best you can until you know better. Then when you know better, do better.",
    "Hustle in silence and let your success make the noise.",
    "If you get tired, learn to rest, not to quit.",
    "Don't look back, you're not going that way.",
    "Every day is a fresh start.",
    "Be the change that you wish to see in the world.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Do not wait to strike till the iron is hot; but make it hot by striking."
];
